// speciesConfig.js - Complete Ecosystem Registry for the Big Scrub Installation
export const bigScrubEcosystem = [
  // --- Gondwanan Ancestries (High Local Persistence / Structured Diversity) ---
  { genus: "Acacia",            species: "melanoxylon",     common: "Blackwood",        origin: "Gondwana", coppice: true,  fleshy: false },
  { genus: "Acradenia",          species: "euodiiformis",    common: "Bonewood",         origin: "Gondwana", coppice: true,  fleshy: false },
  { genus: "Anopterus",          species: "macleayanus",     common: "Macleay Laurel",   origin: "Gondwana", coppice: true,  fleshy: false },
  { genus: "Archirhodomyrtus",   species: "beckleri",      common: "Rose Myrtle",      origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Austrobuxus",        species: "swainii",         common: "Pink Cherry",      origin: "Gondwana", coppice: true,  fleshy: false },
  { genus: "Caldcluvia",         species: "paniculosa",      common: "Soft Corkwood",    origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Callicoma",          species: "serratifolia",    common: "Black Wattle",     origin: "Gondwana", coppice: true,  fleshy: false },
  { genus: "Ceratopetalum",      species: "apetalum",        common: "Coachwood",        origin: "Gondwana", coppice: true,  fleshy: false },
  { genus: "Cryptocarya",        species: "erythroxylon",    common: "Pigeonberry Ash",  origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Cryptocarya",        species: "glaucescens",     common: "Jackwood",         origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Cryptocarya",        species: "meissneriana",    common: "Thick Laurel",     origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Cryptocarya",        species: "obovata",         common: "White Walnut",     origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Cryptocarya",        species: "rigida",          common: "Rose Maple",       origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Daphnandra",         species: "apatela",         common: "Canary Sassafras", origin: "Gondwana", coppice: true,  fleshy: false },
  { genus: "Denhamia",           species: "celastroides",    common: "Orange Boxwood",   origin: "Gondwana", coppice: true,  fleshy: false },
  { genus: "Doryphora",          species: "sassafras",       common: "Golden Sassafras", origin: "Gondwana", coppice: true,  fleshy: false },
  { genus: "Elaeocarpus",        species: "kirtonii",        common: "Silver Quandong",  origin: "Gondwana", coppice: false, fleshy: true  },
  { genus: "Elaeocarpus",        species: "reticulatus",     common: "Blueberry Ash",    origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Endiandra",          species: "crassiflora",     common: "Dorrigo Walnut",   origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Endiandra",          species: "muelleri",        common: "Mueller's Walnut", origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Eupomatia",          species: "laurina",         common: "Bolwarra",         origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Flindersia",         species: "schottiana",      common: "Cudgerie",         origin: "Gondwana", coppice: false, fleshy: false },
  { genus: "Grevillea",          species: "robusta",         common: "Silky Oak",        origin: "Gondwana", coppice: false, fleshy: false },
  { genus: "Nothofagus",         species: "moorei",          common: "Antarctic Beech",  origin: "Gondwana", coppice: true,  fleshy: false },
  { genus: "Orites",             species: "excelsus",        common: "Prickly Ash",      origin: "Gondwana", coppice: false, fleshy: false },
  { genus: "Pennantia",          species: "cunninghamii",    common: "Brown Beech",      origin: "Gondwana", coppice: false, fleshy: true  },
  { genus: "Polyosma",           species: "cunninghamii",    common: "Featherwood",      origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Polyscias",          species: "sambucifolia",    common: "Elderberry Ash",   origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Quintinia",          species: "sieberi",         common: "Possum Wood",      origin: "Gondwana", coppice: true,  fleshy: false },
  { genus: "Rhodamnia",          species: "rubescens",       common: "Scrub Turpentine", origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Sarcopteryx",        species: "stipata",         common: "Steelwood",        origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Schizomeria",        species: "ovata",           common: "White Cherry",     origin: "Gondwana", coppice: true,  fleshy: false },
  { genus: "Stenocarpus",        species: "salignus",        common: "Scrub Beefwood",   origin: "Gondwana", coppice: true,  fleshy: false },
  { genus: "Syzygium",           species: "oleosum",         common: "Blue Lilly Pilly", origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Syzygium",           species: "smithii",         common: "Lilly Pilly",      origin: "Gondwana", coppice: true,  fleshy: true  },
  { genus: "Tasmannia",          species: "insipida",        common: "Pepperbush",       origin: "Gondwana", coppice: false, fleshy: true  },
  { genus: "Tristaniopsis",      species: "collina",         common: "Mountain Water Gum", origin: "Gondwana", coppice: true,  fleshy: false },
  { genus: "Trochocarpa",        species: "laurina",         common: "Tree Heath",       origin: "Gondwana", coppice: true,  fleshy: true  },

  // --- Indo-Malesian Ancestries (Recent Migrants / Lower Homogenized Variation) ---
  { genus: "Acronychia",         species: "oblongifolia",    common: "White Aspen",      origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Acronychia",         species: "pubescens",       common: "Hairy Aspen",      origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Alangium",           species: "villosum",        common: "Black Muskheart",  origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Alphitonia",         species: "excelsa",         common: "Red Ash",          origin: "Indo-Malesia", coppice: false, fleshy: false },
  { genus: "Atractocarpus",      species: "benthamianus",    common: "Native Gardenia",  origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Baloghia",           species: "inophylla",       common: "Brush Bloodwood",  origin: "Indo-Malesia", coppice: true,  fleshy: false },
  { genus: "Breynia",            species: "oblongifolia",    common: "Coffee Bush",      origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Cinnamomum",         species: "oliveri",         common: "Oliver's Sassafras", origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Claoxylon",          species: "australe",        common: "Brittlewood",      origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Dendrocnide",        species: "excelsa",         common: "Giant Stinging Tree", origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Diospyros",          species: "australis",       common: "Black Plum",       origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Diospyros",          species: "pentamera",       common: "Myrtle Ebony",     origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Diploglottis",       species: "cunninghamii",    common: "Native Tamarind",  origin: "Indo-Malesia", coppice: false, fleshy: true  },
  { genus: "Duboisia",           species: "myoporoides",     common: "Corkwood",         origin: "Indo-Malesia", coppice: false, fleshy: true  },
  { genus: "Ehretia",            species: "acuminata",       common: "Koda",             origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Ficus",              species: "coronata",        common: "Sandpaper Fig",    origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Guioa",              species: "semiglauca",      common: "Guioa",            origin: "Indo-Malesia", coppice: false, fleshy: true  },
  { genus: "Homalanthus",        species: "populifolius",    common: "Bleeding Heart",   origin: "Indo-Malesia", coppice: false, fleshy: true  },
  { genus: "Melicope",           species: "micrococca",      common: "White Doughwood",  origin: "Indo-Malesia", coppice: true,  fleshy: false },
  { genus: "Neolitsea",          species: "australiensis",   common: "Green Bolly Gum",  origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Neolitsea",          species: "dealbata",        common: "White Bolly Gum",  origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Pittosporum",        species: "multiflorum",     common: "Orange Thorn",     origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Pittosporum",        species: "revolutum",       common: "Yellow Lantern",   origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Pittosporum",        species: "undulatum",       common: "Sweet Pittosporum", origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Planchonella",       species: "australis",       common: "Black Apple",      origin: "Indo-Malesia", coppice: false, fleshy: true  },
  { genus: "Polyscias",          species: "elegans",         common: "Celery Wood",      origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Polyscias",          species: "murrayi",         common: "Pencil Cedar",     origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Scolopia",           species: "braunii",         common: "Flintwood",        origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Sarcopteryx",        species: "stipata",         common: "Steelwood",        origin: "Indo-Malesia", coppice: true,  fleshy: true  },
  { genus: "Synoum", species: "glandulosum", common: "Scentless Rosewood", origin: "Indo-Malesia", coppice: false, fleshy: true },
{ genus: "Tabernaemontana", species: "pandacaqui", common: "Banana Bush", origin: "Indo-Malesia", coppice: true, fleshy: true },
{ genus: "Toona", species: "ciliata", common: "Red Cedar", origin: "Indo-Malesia", coppice: true, fleshy: false },
{ genus: "Wilkiea", species: "huegeliana", common: "Veiny Wilkiea", origin: "Indo-Malesia", coppice: true, fleshy: true }
];

